name: orange3-text-env
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- scipy
- scikit-learn
- numpy
- gensim>=0.12.3
- setuptools-git
- Orange3>=3.3.9
- beautifulsoup4
- pyqt=5.6.0

- pip:
  - validate_email
  - tweepy
  - simhash
  - wikipedia
  - Sphinx
